### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by amprice83** [learn-co/learn-ide-tree#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 2.2.1
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package, v1.0.17

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Applications/Learn IDE.app/Contents/Resources/app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:69

TypeError: Cannot read property 'getPath' of undefined
    at atom-workspace.onSave (/Applications/Learn IDE.app/Contents/Resources/app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:69:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Learn IDE.app/Contents/Resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/Applications/Learn IDE.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -3:28.2.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -3:18.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:11.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:08.6.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -3:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:41.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:42.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:34.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:33.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:27.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:57.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:57.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45.1.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -0:16.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.1.0 learn-ide:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
update-package-dependencies, v0.10.0 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)
learn-ide, v2.2.1 (active)
learn-ide-tree, v1.0.17 (active)

# Dev
No dev packages
```

I cannot complete the flow control lab without this being fixed. Please help!

Amanda

**Comment by wiredjuice** [comment]
I am in the same position. I cannot save my index.js file in order to execute the pull request. My local tests keep failing.

**Comment by jackconway** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 2.2.1
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package, v1.0.17


### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:69

TypeError: Cannot read property 'getPath' of undefined
    at atom-workspace.onSave (/Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:69:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Users/JackConway/Desktop/Learn IDE.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:30.1.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:28.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:01.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.6.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.3.0 learn-ide:save (div.terminal)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
update-package-dependencies, v0.10.0 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)
learn-ide, v2.2.1 (active)
learn-ide-tree, v1.0.17 (active)

# Dev
No dev packages
```

Same!

**Comment by keiththecomputerguy** [comment]
Having the same issue!
![screen shot 2017-01-18 at 11 49 51 pm](https://cloud.githubusercontent.com/assets/2928450/22095963/5ef8c66a-ddde-11e6-8646-2cb8102bfe2e.png)

**Comment by Lizeee** [comment]
Having the same issue,cannot work on the lab

**Comment by jtnguyen000** [comment]
I just got this same issue and cannot save in my lab. Has there been a solution, or should I keep trying to work past it?

**Comment by Lizeee** [comment]
I uninstalled the IDE completely and re-installed it and it works fine now

**Comment by kkdub** [comment]
Same error, but my IDE was not up-to-date. Restart with update FTW!

**Comment by mirnaio** [comment]
Dealing with same issue now. For me the error message is appearing when I am saving for the second time, i.e. when i'm saving and no changes were made to the file since the previous save.

Does this apply to anyone else?

**Comment by barnettjw** [comment]
In the learn-ide go to the *Packages* menu then *Learn IDE* and finally *Reconnect*
