### ISSUE TITLE
Uncaught TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by jbbreck** [learn-co/learn-ide-tree#57]
[Before submitting, please enter steps to reproduce:]

1. I just pressed control s and now it won't save and just throws this error
2. I was on the arrays lesson

**Learn IDE Package**: 2.5.2
**Learn IDE Core**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.1
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.23

### Stack Trace

Uncaught TypeError: Cannot read property 'send' of undefined

```
At /Users/jacobbreck/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:45

TypeError: Cannot read property 'send' of undefined
    at Connection.module.exports.Connection.send (/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:45:23)
    at Nsync.send (/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:167:28)
    at Nsync.save (/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:289:17)
    at /packages/learn-ide-tree/lib/nsync/initializer.coffee:62:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:29.9.0 core:move-right (input.hidden-input)
     -1:28.1.0 editor:newline (input.hidden-input)
     -1:25.1.0 core:backspace (input.hidden-input)
     -1:23.2.0 autocomplete-plus:confirm (input.hidden-input)
     -1:18.9.0 editor:newline (input.hidden-input)
     -0:58.4.0 core:copy (input.hidden-input)
     -0:56.9.0 core:paste (input.hidden-input)
     -0:37.5.0 core:backspace (input.hidden-input)
     -0:33.3.0 core:cut (input.hidden-input)
     -0:32.3.0 core:backspace (input.hidden-input)
     -0:30 core:paste (input.hidden-input)
     -0:25.3.0 core:cut (input.hidden-input)
     -0:24.7.0 core:backspace (input.hidden-input)
  9x -0:24.1.0 core:move-left (input.hidden-input)
     -0:20.3.0 core:paste (input.hidden-input)
     -0:18.5.0 learn-ide:save (input.hidden-input)
```

### Non-Core Packages

```
learn-ide-notifications 0.66.5 
```

**Comment by ssanusi** [comment]
Uncaught TypeError: Cannot read property 'send' of undefined
/Users/sscode/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:49
Hide Stack Trace
TypeError: Cannot read property 'send' of undefined
    at Connection.module.exports.Connection.send (/Users/sscode/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:49:23)
    at Nsync.send (/Users/sscode/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:167:28)
    at Nsync.save (/Users/sscode/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:289:17)
    at atom-workspace.onSave (/Users/sscode/.atom/packages/learn-ide-tree/lib/nsync/initializer.coffee:62:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Learn IDE 3.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Learn IDE 3.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Learn IDE 3.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Learn IDE 3.app/Contents/Resources/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/Applications/Learn IDE 3.app/Contents/Resources/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
The error was thrown from the learn-ide-tree package. This issue has already been reported.
View Issue
