### ISSUE TITLE
Learn IDE will not work at all, even after complete un/re-install and following prescribed fixes.

### ISSUE THREAD

**Issue by ElphC350** [learn-co/learn-ide-tree#71]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Learn IDE will not work at all. I have reviewed another thread on this same error and tried all the prescribed fixes, nothing works in the slightest.

- I cannot type in the command terminal, even when I pop it out.
- I cannot open the tree view, it does not even toggle via the menu. 
- It will not connect to learn.co or github

**Learn IDE Package**: 2.5.3
**Learn IDE Core**: 2.5.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.5
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.23

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of undefined

```
At /Applications/Learn IDE.app/Contents/Resources/app.asar/node_modules/nsync-fs/lib/connection.js:49

TypeError: Cannot read property 'reset' of undefined
    at Connection.module.exports.Connection.reset (/app.asar/node_modules/nsync-fs/lib/connection.js:49:23)
    at Nsync.resetConnection (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:86:28)
    at /app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:161:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at /app.asar/node_modules/learn-ide/lib/views/status.js:70:34)
```

### Commands

```
     -1:07.6.0 tree-view:toggle (textarea.xterm-helper-textarea)
     -1:01.0 command-palette:toggle (textarea.xterm-helper-textarea)
     -0:57.4.0 editor:toggle-soft-wrap (input.hidden-input)
     -0:55.4.0 tree-view:toggle (input.hidden-input)
     -0:38.5.0 core:backspace (input.hidden-input)
     -0:34.8.0 learn-ide:clear-terminal (div.)
  3x -0:25.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:14 encoding-selector:show (atom-text-editor.editor)
     -0:10.9.0 learn-ide:toggle-popout (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -0:03.5.0 learn-ide:reset-connection (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```

```

### Steps to Reproduce

1. Open the Learn IDE via the 'Open' button on the learn.co website or open manually via the application icon.

**Expected behavior:** The forked lesson to open up and the tree view visible on the left hand side with all the previously forked lesson folders.

**Actual behavior:** The Learn IDE application opens up and then nothing. There is just a blank page with the rotating tool tips. I cannot type in the terminal, and cannot open the tree view or open any files.

**Reproduces how often:** 100% of the time.

### Versions

v2.5.3 - This showed up when I selected 'view version' in the Learn IDE dropdown menu.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ElphC350** [comment]
Well, I tried a complete uninstall (and I mean I went through and manually deleted every possibly related file) on my mac and downloaded a fresh file and reinstalled it. It again didn't work at first but I restarted my comp and it seems to be working now, although the tree is on the right instead of the left, but hey! It works.

To other people having this issue with a Mac and/or who don't know how to manually delete caches and the like. Here are some steps to help you out:

First, make sure you have uninstalled the Learn IDE (drag the icon to the trash).

1. Open your Finder or click on the desktop.
2. On the bar at the top of the screen click 'Go'.
3. While the drop down menu is open, press option/alt and you should see a new option appear: 'Library', between Home and Computer. Like so:

![screen shot 2017-08-06 at 6 17 37 pm](https://user-images.githubusercontent.com/30487453/29055087-0bb2ee94-7b96-11e7-84d3-bb9f248bbd16.png)

Open it. It should look something like this:

![screen shot 2017-08-07 at 5 39 37 pm](https://user-images.githubusercontent.com/30487453/29055315-81522f9c-7b97-11e7-8eb4-d02c56b6252d.png)


4. Go to the search bar in the top right and search for 'github'. After pressing enter, go to the bar below and make sure "Library" is selected instead of 'This Mac'. I deleted everything here, however if you have other programs or anything that might contain 'github' in the filename or file itself you may want to go through and check them. 

After you are done do the same thing for the search terms 'learn', 'learn.co', 'atom' and 'flatiron'.

![screen shot 2017-08-07 at 5 33 33 pm](https://user-images.githubusercontent.com/30487453/29055354-c39d4508-7b97-11e7-97e1-b595775d9927.png)

I deleted everything as far back to when I originally downloaded it (for me it was a month, it might be different for you). And then went through the files under previous dates and found quite a few that were related. (I'm guessing the date on the file(s) caused them to be filed under '2015' and the like?)

5. Go into the library and search through these folders just to make sure everything is gone:

- Application Support
- Caches
- Logs
- Preferences
- WebKit

Hope this helps others who are just starting out and/or don't know how to navigate a mac that well :) (Like me! But one can't complain when someone gets you a wonderful gift.)
