### ISSUE TITLE
Uncaught TypeError: Cannot read property '$ATOM_HOME/.learn-ide/home/moba2k-20620/code/labs/welco...

### ISSUE THREAD

**Issue by moba2k** [learn-co/learn-ide-tree#73]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 2.5.3
**Learn IDE Core**: 2.5.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.23

### Stack Trace

Uncaught TypeError: Cannot read property '/User/Guest/.atom/.learn-ide/home/moba2k-20620/code/labs/welcome-to-learn-5-welcome-000/.git/COMMIT_EDITMSG' of undefined

```
At /User/Guest/Downloads/Learn IDE.app/Contents/Resources/app.asar/node_modules/learn-ide-tree/lib/nsync/atom-helper.js:225

TypeError: Cannot read property '/User/Guest/.atom/.learn-ide/home/moba2k-20620/code/labs/welcome-to-learn-5-welcome-000/.git/COMMIT_EDITMSG' of undefined
    at Object.resolveOpen (/app.asar/node_modules/learn-ide-tree/lib/nsync/atom-helper.js:225:51)
    at /app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:190:27
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/nsync-fs/node_modules/event-kit/lib/emitter.js:82:11)
    at Nsync.opened (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:94:25)
    at /app.asar/node_modules/nsync-fs/lib/onmessage-strategies/open.js:24:18
    at /app.asar/node_modules/nsync-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by moba2k** [comment]
opened learn ide by pressing open from learn.co, while environment was already open.  That's what led to this error message.

**Comment by moba2k** [comment]
Now, all my labs have a -000 attached to the titles.
