### ISSUE TITLE
Uncaught TypeError: Cannot read property 'determineSync' of undefined

### ISSUE THREAD

**Issue by word4wisdom** [learn-co/learn-ide-tree#81]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.24

### Stack Trace

Uncaught TypeError: Cannot read property 'determineSync' of undefined

```
At C:\Users\Joan\.atom\packages\learn-ide-tree\lib\nsync\initializer.coffee:94

TypeError: Cannot read property 'determineSync' of undefined
    at onEditorSave (/packages/learn-ide-tree/lib/nsync/initializer.coffee:94:7)
    at /packages/learn-ide-tree/lib/nsync/initializer.coffee:182:9
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:893:26)
    at Object.saveEditor (/app.asar/node_modules/learn-ide-3-tree/lib/nsync/atom-helper.js:213:27)
    at /app.asar/node_modules/learn-ide-3-tree/lib/nsync/initializer.js:197:27
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/nsync-fs/node_modules/event-kit/lib/emitter.js:82:11)
    at Nsync.updated (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:78:25)
    at close_write (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:49:11)
    at change (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:67:10)
    at onmessage (/app.asar/node_modules/nsync-fs/lib/onmessage.js:47:12)
    at Object.callback (/app.asar/node_modules/nsync-fs/lib/connection.js:18:16)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:615:21
    at Array.map (native)
    at Channel.trigger (/app.asar/node_modules/phoenix/priv/static/phoenix.js:614:10)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1038:26
    at Array.forEach (native)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1037:12
    at Socket.decode (/app.asar/node_modules/phoenix/priv/static/phoenix.js:667:12)
    at Socket.onConnMessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:1023:12)
    at WebSocket.conn.onmessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:826:23)
```

### Commands

```
  2x -1:54.6.0 editor:newline (input.hidden-input)
  3x -1:31.6.0 core:backspace (input.hidden-input)
  2x -1:30.7.0 editor:newline (input.hidden-input)
     -1:27.7.0 core:move-up (input.hidden-input)
     -1:00.8.0 editor:newline (input.hidden-input)
  5x -0:55 core:backspace (input.hidden-input)
     -0:32.1.0 editor:newline (input.hidden-input)
  3x -0:22.7.0 core:move-down (input.hidden-input)
     -0:21.8.0 core:move-up (input.hidden-input)
 11x -0:21.4.0 core:move-left (input.hidden-input)
     -0:19.2.0 core:move-up (input.hidden-input)
  2x -0:18.8.0 core:move-down (input.hidden-input)
  3x -0:16.7.0 core:move-left (input.hidden-input)
     -0:16.1.0 core:move-up (input.hidden-input)
     -0:15.6.0 core:backspace (input.hidden-input)
     -0:14.5.0 learn-ide:save (input.hidden-input)
```

### Non-Core Packages

```
integrated-learn-environment 1.0.0 
learn-ide 2.5.3 
learn-ide-notifications 0.66.5 
learn-ide-tree 1.0.24 
```

**Comment by kaushalpatel778** [comment]
every time i save the work this  error pops up

**Comment by kaushalpatel778** [comment]
C:\Users\kaush\.atom\packages\learn-ide-tree\lib\nsync\initializer.coffee:94
Hide Stack Trace
TypeError: Cannot read property 'determineSync' of undefined
    at onEditorSave (file:///C:/Users/kaush/.atom/packages/learn-ide-tree/lib/nsync/initializer.coffee:94:7)
    at file:///C:/Users/kaush/.atom/packages/learn-ide-tree/lib/nsync/initializer.coffee:182:9
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\src\text-editor.js:893:26)
    at Object.saveEditor (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\learn-ide-3-tree\lib\nsync\atom-helper.js:213:27)
    at C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\learn-ide-3-tree\lib\nsync\initializer.js:197:27
    at Emitter.module.exports.Emitter.emit (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\nsync-fs\node_modules\event-kit\lib\emitter.js:82:11)
    at Nsync.updated (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\nsync-fs\lib\nsync-fs.js:78:25)
    at close_write (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\nsync-fs\lib\onmessage-strategies\change.js:49:11)
    at change (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\nsync-fs\lib\onmessage-strategies\change.js:67:10)
    at onmessage (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\nsync-fs\lib\onmessage.js:47:12)
    at Object.callback (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\nsync-fs\lib\connection.js:18:16)
    at C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\phoenix\priv\static\phoenix.js:615:21
    at Array.map (native)
    at Channel.trigger (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\phoenix\priv\static\phoenix.js:614:10)
    at C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\phoenix\priv\static\phoenix.js:1038:26
    at Array.forEach (native)
    at C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\phoenix\priv\static\phoenix.js:1037:12
    at Socket.decode (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\phoenix\priv\static\phoenix.js:667:12)
    at Socket.onConnMessage (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\phoenix\priv\static\phoenix.js:1023:12)
    at WebSocket.conn.onmessage (C:\Users\kaush\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\phoenix\priv\static\phoenix.js:826:23)
